### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by armandsss** [OpenCageData/scala-opencage-geocoder#2]
Demo app provided in OpenCageClientForwardDemoApp.scala does not seem to be working.

When I try to run:
`sbt run -q "Brandenburg Gate" -k "MY-API-KEY"`

I am receiving following error all the time:

`Running com.github.nmdguerreiro.opencage.geocoder.OpenCageClientForwardDemoApp`
`Error: Missing option --query`
`Error: Missing option --key`
`OpenCageClientApp 0.1`
`Usage: OpenCageClientApp [options]`
`  -q, --query <value>  the query you want issue`
`  -k, --key <value>    your authentication key`
`Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"`
`java.lang.RuntimeException: Nonzero exit code: 1`
`        at scala.sys.package$.error(package.scala:27)`
`[trace] Stack trace suppressed: run last compile:run for the full output.`
`[error] (compile:run) Nonzero exit code: 1`
`[error] Total time: 1 s, completed Jul 10, 2018 12:04:19 PM`

Any ideas what could be wrong ? Seems that provided `query` & `key` does not want to parse.

**Comment by tsamaya** [comment]
Hi,
it works for me using:
```bash
sbt "runMain com.github.nmdguerreiro.opencage.geocoder.OpenCageClientForwardDemoApp --query \"Brandenburg Gate\" --key \"MY-API-KEY\""
```

the example is in this repository https://github.com/tsamaya/opencage-scala-client-example
